name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - name: Run tests
        run: zig build test

      - name: Run all examples
        run: zig build -Dbuild-examples=true run-all-examples
